version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanagerpassword
      POSTGRES_DB: taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # FastAPI backend
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://taskmanager:taskmanagerpassword@db:5432/taskmanager
      - SECRET_KEY=your-secret-key-here-change-in-production

  # React frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: